name: Job output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubyntu-latest

    steps:
      - name: set output
        id: set-output
        run: echo "name=testname" >> $GITHUB_OUTPUT

      - name: access output
        run: echo "name is   $ {{ steps.set-output.outputs.name }} "
  
